### ISSUE TITLE
ایجاد DateRange

### ISSUE THREAD

**Issue by ehsan957** [mousavian/bootstrap-jalali-datepicker#17]
چطور میشه minDate یه datepicker1 را برمبنای تاریخ انتخاب شده روی datepicker2 قرار داد؟

**Comment by aligilan** [comment]
سلام، احتمالا این جواب برای شما دیگه کاربرد نداشته باشه.
ولی برای کسانی که گذرشان به اینجا افتاد:

اول لینک داکیومنت براتون میفرستم:‌
