### ISSUE TITLE
افزایش بازه انتخاب سال

### ISSUE THREAD

**Issue by mr-kiani** [mousavian/bootstrap-jalali-datepicker#21]
حداقل سال الان 1388 هست چطوره میتونم بازشو بیشتر کنم مثلا از 1330 تا الان؟

**Comment by mousavian** [comment]
سلام @mr-kiani ,
میتونی از `yearRange` استفاده کنی:

```javascript
 $("#datepicker4").datepicker({
    yearRange: '1300:1330',
    changeMonth: true,
    changeYear: true
});
```

برای 1330 تا الان میتونی اینطوری مشخص کنی:
`yearRange: '1330:',`
