### ISSUE TITLE
چگونه تاریخ انتخاب شده را به میلادی برگردانیم؟

### ISSUE THREAD

**Issue by SaeedSoltoon** [mousavian/bootstrap-jalali-datepicker#3]
سلام خیلی ممنون به خاطر پلاگین زیباتون
اگه امکانش هست میشه توضیح بدید چطوری تاریخی که انتخاب شده رو به میلادی برگردونم؟

**Comment by mousavian** [comment]
@SaeedSoltoon 
میتونید از دوتا تابع 
**jd_to_gregorian** و **persian_to_jd**
استفاده کنید.
```
jd_to_gregorian( persian_to_jd(year, month, day ) );
```

**Comment by mtahani** [comment]
سلام دوست عزیز
من میخوام قبل از سابمیت فرم این تاریخ به میلادی تبدیل بشه 
این کار را باید دستی انجام بدم و یا اینکه برای این موضوع تنظیمی وجود دارد؟
