### ISSUE TITLE
more than one date input

### ISSUE THREAD

**Issue by tuytoosh** [mousavian/bootstrap-jalali-datepicker#6]
Hi . I am using a form with more than one date inputs. for example 3 inputs...
it works in first input but is not working in others...

(I have many low knowledge about Jquery) 
what i must do?

**Comment by tuytoosh** [comment]
my problem solved with using `class` instead of `id`   :)

thanks for your great package

**Comment by mousavian** [comment]
@tuytoosh Basically `id`s refer to just 1 element while `class`es are referred to a group of elements.
