### ISSUE TITLE
inline datepicker is not jajali and persian

### ISSUE THREAD

**Issue by miladd3** [mousavian/bootstrap-jalali-datepicker#8]
in date picker format in inputs is ok but when i add it to a div to show inline calendar its goes in English
![capture](https://cloud.githubusercontent.com/assets/1721290/12421824/2e26efd2-bed9-11e5-8869-9dce108b47f3.JPG)

**Comment by mousavian** [comment]
@miladd3 I tested inline one [here](https://jsfiddle.net/b560s26t/) and it works fine.

If you still have problem, provide more information about how you use it.
